=== KingKrimson/MusicMashup/nbproject/private/retriever/www.cems.uwe.ac.uk/_p-chatterjee/modules/dsa/group_metafile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <!-- 
    ==================================================================
    This is the schema for the assignment xml file.
    See dsa_metafile_example.xml for a valid example instance. 
    Ensure your group_metafile.xml is validated against this schema 
    using Oxygen or some other validator.
    DO NOT EDIT OR CHANGE THIS FILE UNDER ANY CIRCUMSTANCES 
    ==================================================================
  -->

  <!-- element definitions - adopts the russian 
    doll approach with only one top level element -->
  <xs:element name="dsa_metafile">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="module">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="titleType"/>
              <xs:element name="year" type="yearType"/>
              <xs:element name="hand_in" type="hand_inType"/>
              <xs:element name="spec_url" type="urlType"/>
            </xs:sequence>
            <xs:attribute name="acronymn" use="required" type="module_acronymnType"/>
            <xs:attribute name="id" use="required" type="module_idType"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="group">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="member" minOccurs="2" maxOccurs="4">
                <xs:complexType>
                  <xs:attribute name="id" use="required" type="student_idType"/>
                  <xs:attribute name="name" use="required" type="nameType"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="workshop">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="daytime" type="daytimeType"/>
                    <xs:element name="tutor" type="tutorType" minOccurs="2" maxOccurs="2"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="component" minOccurs="4" maxOccurs="12">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="contributor" minOccurs="1" maxOccurs="4">
                      <xs:complexType>
                        <xs:attribute name="id" use="required" type="student_idType"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="description" type="txtType"/>
                    <xs:element name="problems" type="txtType"/>
                    <xs:element name="solutions" type="txtType"/>
                    <xs:element name="hours_effort" type="hours_effortType"/>
                  </xs:sequence>
                  <xs:attribute name="type" use="required" type="gcomponentType"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="individual" minOccurs="2" maxOccurs="4">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="component" minOccurs="1" maxOccurs="3">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="description" type="txtType"/>
                    <xs:element name="problems" type="txtType"/>
                    <xs:element name="solutions" type="txtType"/>
                    <xs:element name="hours_effort" type="hours_effortType"/>
                  </xs:sequence>
                  <xs:attribute name="type" use="required" type="icomponentType"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="student_idType"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="application">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="base_url" type="xs:anyURI"/>
              <xs:element name="technologies">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tech" minOccurs="3" maxOccurs="8" type="techType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="config_source" type="xs:anyURI"/>
              <xs:element name="dm_source" type="xs:anyURI"/>
              <xs:element name="source_files">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="file" minOccurs="1" maxOccurs="8">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="purpose" type="xs:string"/>
                          <xs:element name="source_url" type="xs:anyURI"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="overall_comments" type="txtType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Type definitions -->
  <!-- element types -->
  <xs:simpleType name="titleType">
    <xs:restriction base="xs:string">
      <xs:pattern value="Data Schemas &amp; Applications"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="yearType">
    <xs:restriction base="xs:string">
      <xs:pattern value="2013"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hand_inType">
    <xs:restriction base="xs:date">
      <xs:pattern value="2013-02-28"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="urlType">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http://www.cems.uwe.ac.uk/~p-chatterjee/2011/dsa/DSA_CW_Spec.html"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="nameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="24"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="daytimeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Monday 09:00"/>
      <xs:enumeration value="Monday 12:00"/>
      <xs:enumeration value="Monday 13:00"/>
      <xs:enumeration value="Tuesday 09:00"/>
      <xs:enumeration value="Tuesday 12:00"/>
      <xs:enumeration value="Tuesday 13:00"/>
      <xs:enumeration value="Wednesday 11.00"/>
      <xs:enumeration value="Wednesday 12.00"/>
      <xs:enumeration value="Wednesday 14.00"/>
      <xs:enumeration value="Thursday 13:00"/>
      <xs:enumeration value="Friday 13:00"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tutorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="GW"/>
      <xs:enumeration value="KD"/>
      <xs:enumeration value="PM"/>
      <xs:enumeration value="PC"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="txtType">
    <xs:restriction base="xs:string">
      <xs:minLength value="80"/>
      <xs:maxLength value="5000"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hours_effortType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="120"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="techType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="php"/>
      <xs:enumeration value="xml"/>
      <xs:enumeration value="xslt"/>
      <xs:enumeration value="html5"/>
      <xs:enumeration value="xhtml"/>
      <xs:enumeration value="css"/>
      <xs:enumeration value="javascript"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
  <!--- end of element types -->

  <!-- attribute types -->
  <xs:simpleType name="module_idType">
    <xs:restriction base="xs:string">
      <xs:pattern value="UFCEKG-20-2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="module_acronymnType">
    <xs:restriction base="xs:string">
      <xs:pattern value="DSA"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="gcomponentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Database Design"/>
      <xs:enumeration value="Database Implementation"/>
      <xs:enumeration value="HTML Markup"/>
      <xs:enumeration value="CSS Design"/>
      <xs:enumeration value="PHP Coding"/>
      <xs:enumeration value="Javascript Coding"/>
      <xs:enumeration value="XML Markup"/>
      <xs:enumeration value="Other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="icomponentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Calender"/>
      <xs:enumeration value="News"/>
      <xs:enumeration value="Genre Background"/>
      <xs:enumeration value="Map"/>
      <xs:enumeration value="Tracks"/>
      <xs:enumeration value="Videos"/>
      <xs:enumeration value="Social Media"/>
      <xs:enumeration value="Other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="student_idType">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-9]{8}"/>
    </xs:restriction>
  </xs:simpleType>
  <!--- end of attribute types -->
</xs:schema>
<!-- DSA Assignment Schema File, 2013 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== KingKrimson/MusicMashup/XML/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<dsa_metafile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="http://www.cems.uwe.ac.uk/~p-chatterjee/modules/dsa/group_metafile.xsd">
    <!-- Validates in Oxygen XML. -->

    <!-- The following is the assignment metadata (not to be changed) -->
    <module id="UFCEKG-20-2" acronymn="DSA">
        <title>Data Schemas &amp; Applications</title>
        <year>2013</year>
        <hand_in>2013-02-28</hand_in>
        <spec_url>http://www.cems.uwe.ac.uk/~p-chatterjee/2011/dsa/DSA_CW_Spec.html</spec_url>
    </module>
    <!-- end of metadata section -->

    <!-- Group Section -->
    <group>
        <member id="11008259" name="Andrew Brown"/>
        <member id="11010631" name="Chris Harpum"/>
        <member id="11017625" name="Adrien Clark"/>
        <member id="11034844" name="Tom Mc Fadden"/>
        <workshop>
            <daytime>Wednesday 11.00</daytime>
            <tutor>PM</tutor>
            <tutor>GW</tutor>
        </workshop>
        <!-- Each student should have contributed to one or more components -->
        <component type="Database Design">
            <contributor id="11008259"/>
            <contributor id="11017625"/>
            <contributor id="11034844"/>
            <!-- the following text fields allow for between 80 and 300 characters -->
            <description>Our group used the QSEE modelling tool to model a 2NF database with 
                the appropriate tables (artists, users, artistfavourites, etc.), 
                fields, primary keys and foreign keys. The workshop example based 
                on modelling a database for a quilt website was very 
                useful at aiding us in this task.
            </description>
            <problems>The design was fairly straight forward, and we did it with
                little to no problems. The only potential issue is the fact
                that QSEE doesn't support some datatypes we wanted to use in 
                MySQL; for instance, QSEE doesn't support 'datetime'.
            </problems>
            <solutions>For the model, we represented 'datetime' as 'timestamp,'
                and added a little comment box stating that they should
                be changed to 'datetime' in the physical database. This ensured
                that there was no ambiguity.
            </solutions>
            <!-- integer required between 1 and 120 -->
            <hours_effort>3</hours_effort>
        </component>
        <component type="Database Implementation">
            <contributor id="11008259"/>
            <contributor id="11034844"/>
            <description>Creating the initial MySQL database was really easy, as QSEE
                allowed us to export the design as a text file, which
                could be imported into PHPMyAdmin. From there, we
                hand populated the database with artists, albums,
                users, tracks, and various favourites(making sure to 
                include the correct/valid foreign keys) again using 
                PHPMyAdmin.
            </description>
            <problems>Intially, importing the text file into the database didn't work.
                This was because of the way that QSEE exported the file: it
                included comments in a non MySQL compatable style.
            </problems>
            <solutions>We opened the text file in notepad++, and stripped the comments.
                We then copied the remaining text, and executed it as a query,
                which was successful.
            </solutions>
            <hours_effort>4</hours_effort>
        </component>
        <component type="HTML Markup">
            <contributor id="11008259"/>
            <description>We decided to use HTML5 instead of XHTML, as HTML5 had some useful features, such
                as the 'hint' attribute for textboxes in forms. In XHTML, this attribute isn't supported,
                and would have to be replaced by javascript.
            </description>
            <problems>Since we echo a lot of HTML5 in PHP so that we can output 
                variables directly, the formatting of the HTML5 isn't very
                readable. If the user wanted to view the source using a browser, 
                they'd be in for a nasty shock.
            </problems>
            <solutions>We could have used PHP's heredoc operator to output literal
                Strings. However, that leads to some unpleasent formatting
                in the PHP code. As developers, we felt that it was more important
                that the PHP was readable for us, rather than the HTML
                being more readable by the users. We also output newlines at the
                end of each HTML5 echo statement.
            </solutions>
            <hours_effort>6</hours_effort>
        </component>
        <component type="PHP Coding">
            <contributor id="11008259"/>
            <contributor id="11010631"/>
            <description>Using PHP allowed us to create a dynamic, database driven site.
                by pulling data from the database we were able to show all of our albums,
                artists, tracks, users and favourites. We also implemented things
                like user login/registration and favouriting.
            </description>
            <problems>None of us had used PHP before, but it proved to be a very 
                easy language to learn. The only issues we encountered
                were the standard programming ones, like syntax and logic
                errors.
            </problems>
            <solutions>We solved these issues by studying php's syntax, double checking our code,
                and using Netbean's PHP debugger.
            </solutions>
            <hours_effort>12</hours_effort>
        </component>
        <component type="Javascript Coding">
            <contributor id="11008259"/>
            <description>We used javascript for ajax calls, which we use for sorting
                the tracks on the track page without reloading the page.
            </description>
            <problems>The method of creating and using a XMLHttpRequest object in pure
                javascript can be quite confusing.
            </problems>
            <solutions>There's some example code in the coursebook; we decided to
                use it as a starting point. It has been credited in the 
                source code comments.
            </solutions>
            <hours_effort>3</hours_effort>
        </component>
        <component type="CSS Design">
            <contributor id="11008259"/>
            <description>Since this is an alternative rock site, we decided to
                use a basic 'grungy' style for it. We chose an appropriate
                font for our logo, and wrote a stylesheet that nicely partitions
                up all of the appropriate sections.
            </description>
            <problems> None of us were very good at styling or writing CSS stylesheets,
                This posed a problem, as a dynamic website like this that doesn't have any
                formatting is almost unusable.
            </problems>
            <solutions> We decided that using a functional but plain stylesheet was
                preferable to spending hours creating a pretty website.
                to pretty up the site. We took the stylesheet 
                from Andrew's previous website, and used that as a base. 
                This has been noted in the CSS comments. 
            </solutions>
            <hours_effort>3</hours_effort>
        </component>
        <component type="XML Markup">
            <contributor id="11008259" />
            <description>As the website was required a valid RSS 2.0 feed of the
                most recently favourited artists, we used a php script to write the 
                feed based on the favourites that we have in our database. We also
                used XML for this metafile.
            </description>
            <problems>We weren't entirely sure how to construct a valid RSS
                feed, or how to actually present it once it had been
                created.
            </problems>
            <solutions>We looked up the RSS specification and schema online, so 
                that we knew how to create a valid RSS 2.0 feed. We decided
                that after the favourites had been processed and put into the feed,
                we would just present the resulting file as is (with no accompanying HTML), 
                as that is how most sites format their RSS feeds.
            </solutions>
            <hours_effort>2</hours_effort>
        </component>
    </group>

    <!-- Individual components are listed here -->
    <individual id="11008259">
        <component type="Social Media">
            <description>This widget uses Twitter's search API to search Twitter 
                for the artist of the 'item' that the user  is currently 
                viewing (or 'AlternativeRock' if they are not looking 
                at an artist, album or track.) Twitter returns the tweets 
                as a json string, which the widget then evaluates, 
                parses, and displays in a user-readable format.
            </description>
            <problems>Twitter's search API has a rate limit of 180 requests for 15
                minute intervals. Everytime a page is reloaded, the widget
                would make a new twitter query. If multiple users were accessing
                the site, then this means twitter would eventually stop
                letting the widget query it.
            </problems>
            <solutions>For the rate limit, I decided that the best solution would
                be to cache the json strings in their own database table, and only
                query twitter for the json if it has been 3 minutes since
